approach: 
  type: stat | ml | ml-entities
  displayName: Search Term Extraction Approach
  description: Defines the approach to be used for generating the search query. "stat" refers to the statistical approach, "ml" to the neural network without restrictions and "ml-entities" to the neural network that only considers Calais entities as valid search terms.