sortOrder: 
  type: best_match | most_popular | newest
  default: most_popular
  displayName: Sort Order
  description: Image sort order that is applied by the Getty API (see [Getty Docs](https://developers.gettyimages.com/docs/#operation/Search_GetImagesByPhrase))