threshold: 
  type: number
  default: 0.5
  minimum: 0.0
  maximum: 1.0
  displayName: Threshold
  description: Probability threshold that defines which terms are considered for query generation and which are discarded